export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_REPOS_SUCCESS = 'LOAD_REPOS_SUCCESS';
export const LOAD_PERSONALINFO_SUCCESS = 'LOAD_PERSONALINFO_SUCCESS';
export const LOAD_WORKHISTORY_SUCCESS = 'LOAD_WORKHISTORY_SUCCESS';
